# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site.

# Theme Settings
# 깃허브 기본 테마(primer) 대신 Minimal Mistakes를 사용하도록 강제 설정합니다.
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" 

# Site Settings
locale                   : "ko-KR"
direction                : "ltr"
title                    : "AI"
title_separator          : " | "
subtitle                 : "AI가 만듦"
name                     : "박지현"
description              : "개발 기록 및 포폴"
url                      : "https://Jerry97s.github.io"
baseurl                  : "" 
repository               : "Jerry97s/Jerry97s.github.io"
teaser                   : 
logo                     : 
masthead_title           : 
breadcrumbs              : false
words_per_minute         : 200
enable_copy_code_button  : true

# Site Author
author:
  name             : "박지현"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "적응력 좋고 긍정적인 개발자입니다. 개발 하는 모든거에 관심이 많습니다."
  location         : "South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Jerry97s"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations: ['import']

# Outputting
permalink: /:categories/:title/
timezone: "Asia/Seoul"

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
